server.port: 8082

spring:
  application.name: app-boot-2
  sleuth:
    enabled: true
    propagation.type: w3c,b3
    # All traces should be sent to latency analysis tool
    sampler.probability: 1
  zipkin:
    enabled: true
    # default is localhost
    baseUrl: http://tempo:9411/api/v2/spans


management:
  endpoints.web.exposure.include: '*'
  endpoint.health.probes.enabled: true
  # For Exemplars to work we need histogram buckets
  metrics.distribution.percentiles-histogram.http.server.requests: true


# traceID and spanId are predefined MDC keys - we want the logs to include them
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
