#
# for local build, run a container based on ubuntu:20.04
#     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/src:/src -it ubuntu:20.04
# then install docker binary in container
#     curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
#
FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --fix-missing --no-install-recommends \
    ca-certificates \
    curl \
    unzip \
    zip \
    build-essential \
    zlib1g-dev

# to test manually
# export MAVEN_VERSION="3.8.6" && export GRAALVM_VERSION="22.3.r17-nik"

ARG MAVEN_VERSION="3.8.6"
ARG GRAALVM_VERSION="22.3.r17-nik"
RUN curl -s "https://get.sdkman.io" | bash
RUN source $HOME/.sdkman/bin/sdkman-init.sh && \
    yes | sdk install maven $MAVEN_VERSION && \
    yes | sdk install java $GRAALVM_VERSION && \
    rm -rf $HOME/.sdkman/archives/* && \
    rm -rf $HOME/.sdkman/tmp/* && \
    source $HOME/.sdkman/bin/sdkman-init.sh
