#
# for local build, run a container based on ubuntu:20.04
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ~/src:/src -it ubuntu:20.04
#
FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --fix-missing --no-install-recommends \
    ca-certificates \
    curl \
    unzip \
    zip \
    build-essential \
    zlib1g-dev

# to test manually
# export MAVEN_VERSION="3.8.6" && export GRAALVM_VERSION="22.3.r17-nik"

ARG MAVEN_VERSION="3.8.6"
ARG GRAALVM_VERSION="22.3.r17-nik"
RUN curl -s "https://get.sdkman.io" | bash
RUN source $HOME/.sdkman/bin/sdkman-init.sh && \
    yes | sdk install maven $MAVEN_VERSION && \
    yes | sdk install java $GRAALVM_VERSION && \
    rm -rf $HOME/.sdkman/archives/* && \
    rm -rf $HOME/.sdkman/tmp/* && \
    source $HOME/.sdkman/bin/sdkman-init.sh

# to use host's docker
#RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

# app-server build
#RUN mvn -Pnative -pl app-server native:compile
#RUN bash -c "cd app-server && docker build -t app-server:0.0.1-SNAPSHOT . "

# app-boot-3 build
#RUN mvn -Pnative -pl app-boot-3 native:compile
#RUN bash -c "cd app-boot-3 && docker build -t app-boot-3:0.0.1-SNAPSHOT . "
