global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['ide:7654','ide:6543','ide:8081', 'ide:8082', 'app-client:6543', 'app-server:7654', 'app-boot-3:8081', 'app-boot-2:8082']
